defmodule CoreEvents.Repo.Migrations.InitialAshResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:name, :text, null: false)
      add(:starts_at, :utc_datetime, null: false)
      add(:ends_at, :utc_datetime)
      add(:venue, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:events))
  end
end
