import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :api_gateway, ApiGatewayWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "qRP/5Cr6J8tgU/hJpOhdg1IIc0x9zm09nFIQFCk1BDaWVpC3Yym+F4Ig3UiMLhYH",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :api_gateway, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Dev DB URLs for each repo (override with env vars if needed)
config :core_events, CoreEvents.Repo,
  url:
    System.get_env("CORE_EVENTS_DATABASE_URL") ||
      "ecto://postgres:postgres@localhost:5432/core_events_dev",
  pool_size: 10

config :core_users, CoreUsers.Repo,
  url:
    System.get_env("CORE_USERS_DATABASE_URL") ||
      "ecto://postgres:postgres@localhost:5432/core_users_dev",
  pool_size: 10

config :core_tickets, CoreTickets.Repo,
  url:
    System.get_env("CORE_TICKETS_DATABASE_URL") ||
      "ecto://postgres:postgres@localhost:5432/core_tickets_dev",
  pool_size: 10

# Dev database configs (override with *_DATABASE_URL env vars as needed)
config :core_events, CoreEvents.Repo,
  url:
    System.get_env("CORE_EVENTS_DATABASE_URL") ||
      "ecto://postgres:postgres@localhost:5432/core_events_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :core_users, CoreUsers.Repo,
  url:
    System.get_env("CORE_USERS_DATABASE_URL") ||
      "ecto://postgres:postgres@localhost:5432/core_users_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :core_tickets, CoreTickets.Repo,
  url:
    System.get_env("CORE_TICKETS_DATABASE_URL") ||
      "ecto://postgres:postgres@localhost:5432/core_tickets_dev",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Oban in dev uses the users repo for now (can switch to dedicated repo later)
config :messaging, Oban,
  repo: CoreUsers.Repo,
  queues: [default: 10],
  plugins: [Oban.Plugins.Pruner]
