defmodule CoreTickets.Repo.Migrations.InitialAshResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:event_id, :bigint, null: false)
      add(:user_id, :bigint, null: false)
      add(:price_cents, :bigint, null: false)
      add(:status, :text, null: false, default: "reserved")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:tickets))
  end
end
