defmodule CoreTickets.Repo.Migrations.AddTicketOutboxMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ticket_outbox_messages, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:topic, :text, null: false)
      add(:event_type, :text, null: false)
      add(:payload, :map, null: false)
      add(:published_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:ticket_outbox_messages))
  end
end
