SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS ( SELECT * FROM sys.schemas WHERE name = N'User' )
   EXEC('CREATE SCHEMA [User]');
GO

CREATE TABLE [User].[Users](
    [Id] [uniqueidentifier] NOT NULL,
    [FullName] [nvarchar](max) NOT NULL,
    [Email] [nvarchar](max) NOT NULL,
    CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED
(
[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
    GO